import '../models/select_item.dart';

class Country {
  Country._();
  static List<SelectItem> countries = [
    SelectItem(id: '190', name: 'Việt Nam (Vietnam)'),
    SelectItem(id: '1', name: 'Afghanistan'),
    SelectItem(id: '2', name: 'Albania'),
    SelectItem(id: '3', name: 'Algeria'),
    SelectItem(id: '4', name: 'Andorra'),
    SelectItem(id: '5', name: 'Angola'),
    SelectItem(id: '6', name: 'Antigua và Barbuda'),
    SelectItem(id: '7', name: 'Argentina'),
    SelectItem(id: '8', name: 'Armenia'),
    SelectItem(id: '9', name: 'Úc (Australia)'),
    SelectItem(id: '10', name: 'Áo (Austria)'),
    SelectItem(id: '11', name: 'Azerbaijan'),
    SelectItem(id: '12', name: 'Bahamas'),
    SelectItem(id: '13', name: 'Bahrain'),
    SelectItem(id: '14', name: 'Bangladesh'),
    SelectItem(id: '15', name: 'Barbados'),
    SelectItem(id: '16', name: 'Belarus'),
    SelectItem(id: '17', name: 'Bỉ (Belgium)'),
    SelectItem(id: '18', name: 'Belize'),
    SelectItem(id: '19', name: 'Benin'),
    SelectItem(id: '20', name: 'Bhutan'),
    SelectItem(id: '21', name: 'Bolivia'),
    SelectItem(id: '22', name: 'Bosnia và Herzegovina'),
    SelectItem(id: '23', name: 'Botswana'),
    SelectItem(id: '24', name: 'Brasil (Brazil)'),
    SelectItem(id: '25', name: 'Brunei'),
    SelectItem(id: '26', name: 'Bulgaria'),
    SelectItem(id: '27', name: 'Burkina Faso'),
    SelectItem(id: '28', name: 'Burundi'),
    SelectItem(id: '29', name: 'Cabo Verde'),
    SelectItem(id: '30', name: 'Campuchia (Cambodia)'),
    SelectItem(id: '31', name: 'Cameroon'),
    SelectItem(id: '32', name: 'Canada'),
    SelectItem(id: '33', name: 'Cộng hòa Trung Phi (Central African Republic)'),
    SelectItem(id: '34', name: 'Chad'),
    SelectItem(id: '35', name: 'Chile'),
    SelectItem(id: '36', name: 'Trung Quốc (China)'),
    SelectItem(id: '37', name: 'Colombia'),
    SelectItem(id: '38', name: 'Comoros'),
    SelectItem(
        id: '39',
        name: 'Cộng hòa Dân chủ Congo (Democratic Republic of the Congo)'),
    SelectItem(id: '40', name: 'Cộng hòa Congo (Republic of the Congo)'),
    SelectItem(id: '41', name: 'Costa Rica'),
    SelectItem(id: '42', name: 'Croatia'),
    SelectItem(id: '43', name: 'Cuba'),
    SelectItem(id: '44', name: 'Síp (Cyprus)'),
    SelectItem(id: '45', name: 'Cộng hòa Séc (Czech Republic)'),
    SelectItem(id: '46', name: 'Đan Mạch (Denmark)'),
    SelectItem(id: '47', name: 'Djibouti'),
    SelectItem(id: '48', name: 'Dominica'),
    SelectItem(id: '49', name: 'Cộng hòa Dominican'),
    SelectItem(id: '50', name: 'Đông Timor (East Timor)'),
    SelectItem(id: '51', name: 'Ecuador'),
    SelectItem(id: '52', name: 'Ai Cập (Egypt)'),
    SelectItem(id: '53', name: 'El Salvador'),
    SelectItem(id: '54', name: 'Guinea Xích Đạo (Equatorial Guinea)'),
    SelectItem(id: '55', name: 'Eritrea'),
    SelectItem(id: '56', name: 'Estonia'),
    SelectItem(id: '57', name: 'Ethiopia'),
    SelectItem(id: '58', name: 'Fiji'),
    SelectItem(id: '59', name: 'Phần Lan (Finland)'),
    SelectItem(id: '60', name: 'Pháp (France)'),
    SelectItem(id: '61', name: 'Gabon'),
    SelectItem(id: '62', name: 'Gambia'),
    SelectItem(id: '63', name: 'Georgia'),
    SelectItem(id: '64', name: 'Đức (Germany)'),
    SelectItem(id: '65', name: 'Ghana'),
    SelectItem(id: '66', name: 'Hy Lạp (Greece)'),
    SelectItem(id: '67', name: 'Grenada'),
    SelectItem(id: '68', name: 'Guatemala'),
    SelectItem(id: '69', name: 'Guinea'),
    SelectItem(id: '70', name: 'Guinea-Bissau'),
    SelectItem(id: '71', name: 'Guyana'),
    SelectItem(id: '72', name: 'Haiti'),
    SelectItem(id: '73', name: 'Honduras'),
    SelectItem(id: '74', name: 'Hungary'),
    SelectItem(id: '75', name: 'Iceland'),
    SelectItem(id: '76', name: 'Ấn Độ (India)'),
    SelectItem(id: '77', name: 'Indonesia'),
    SelectItem(id: '78', name: 'Iran'),
    SelectItem(id: '79', name: 'Iraq'),
    SelectItem(id: '80', name: 'Ireland'),
    SelectItem(id: '81', name: 'Israel'),
    SelectItem(id: '82', name: 'Ý (Italy)'),
    SelectItem(id: '83', name: 'Jamaica'),
    SelectItem(id: '84', name: 'Nhật Bản (Japan)'),
    SelectItem(id: '85', name: 'Jordan'),
    SelectItem(id: '86', name: 'Kazakhstan'),
    SelectItem(id: '87', name: 'Kenya'),
    SelectItem(id: '88', name: 'Kiribati'),
    SelectItem(id: '89', name: 'Bắc Triều Tiên (North Korea)'),
    SelectItem(id: '90', name: 'Hàn Quốc (South Korea)'),
    SelectItem(id: '91', name: 'Kuwait'),
    SelectItem(id: '92', name: 'Kyrgyzstan'),
    SelectItem(id: '93', name: 'Lào (Laos)'),
    SelectItem(id: '94', name: 'Latvia'),
    SelectItem(id: '95', name: 'Lebanon'),
    SelectItem(id: '96', name: 'Lesotho'),
    SelectItem(id: '97', name: 'Liberia'),
    SelectItem(id: '98', name: 'Libya'),
    SelectItem(id: '99', name: 'Liechtenstein'),
    SelectItem(id: '100', name: 'Lithuania'),
    SelectItem(id: '101', name: 'Luxembourg'),
    SelectItem(id: '102', name: 'Macedonia (Bắc Macedonia)'),
    SelectItem(id: '103', name: 'Madagascar'),
    SelectItem(id: '104', name: 'Malawi'),
    SelectItem(id: '105', name: 'Malaysia'),
    SelectItem(id: '106', name: 'Maldives'),
    SelectItem(id: '107', name: 'Mali'),
    SelectItem(id: '108', name: 'Malta'),
    SelectItem(id: '109', name: 'Quần đảo Marshall (Marshall Islands)'),
    SelectItem(id: '110', name: 'Mauritania'),
    SelectItem(id: '111', name: 'Mauritius'),
    SelectItem(id: '112', name: 'Mexico'),
    SelectItem(id: '113', name: 'Micronesia'),
    SelectItem(id: '114', name: 'Moldova'),
    SelectItem(id: '115', name: 'Monaco'),
    SelectItem(id: '116', name: 'Mongolia'),
    SelectItem(id: '117', name: 'Montenegro'),
    SelectItem(id: '118', name: 'Morocco'),
    SelectItem(id: '119', name: 'Mozambique'),
    SelectItem(id: '120', name: 'Myanmar (Burma)'),
    SelectItem(id: '121', name: 'Namibia'),
    SelectItem(id: '122', name: 'Nauru'),
    SelectItem(id: '123', name: 'Nepal'),
    SelectItem(id: '124', name: 'Hà Lan (Netherlands)'),
    SelectItem(id: '125', name: 'New Zealand'),
    SelectItem(id: '126', name: 'Nicaragua'),
    SelectItem(id: '127', name: 'Niger'),
    SelectItem(id: '128', name: 'Nigeria'),
    SelectItem(id: '129', name: 'Na Uy (Norway)'),
    SelectItem(id: '130', name: 'Oman'),
    SelectItem(id: '131', name: 'Pakistan'),
    SelectItem(id: '132', name: 'Palau'),
    SelectItem(id: '133', name: 'Panama'),
    SelectItem(id: '134', name: 'Papua New Guinea'),
    SelectItem(id: '135', name: 'Paraguay'),
    SelectItem(id: '136', name: 'Peru'),
    SelectItem(id: '137', name: 'Philippines'),
    SelectItem(id: '138', name: 'Ba Lan (Poland)'),
    SelectItem(id: '139', name: 'Bồ Đào Nha (Portugal)'),
    SelectItem(id: '140', name: 'Qatar'),
    SelectItem(id: '141', name: 'Romania'),
    SelectItem(id: '142', name: 'Nga (Russia)'),
    SelectItem(id: '143', name: 'Rwanda'),
    SelectItem(id: '144', name: 'Saint Kitts và Nevis'),
    SelectItem(id: '145', name: 'Saint Lucia'),
    SelectItem(id: '146', name: 'Saint Vincent và Grenadines'),
    SelectItem(id: '147', name: 'Samoa'),
    SelectItem(id: '148', name: 'San Marino'),
    SelectItem(id: '149', name: 'São Tomé và Príncipe'),
    SelectItem(id: '150', name: 'Ả Rập Xê Út (Saudi Arabia)'),
    SelectItem(id: '151', name: 'Senegal'),
    SelectItem(id: '152', name: 'Serbia'),
    SelectItem(id: '153', name: 'Seychelles'),
    SelectItem(id: '154', name: 'Sierra Leone'),
    SelectItem(id: '155', name: 'Singapore'),
    SelectItem(id: '156', name: 'Slovakia'),
    SelectItem(id: '157', name: 'Slovenia'),
    SelectItem(id: '158', name: 'Solomon Islands'),
    SelectItem(id: '159', name: 'Somalia'),
    SelectItem(id: '160', name: 'Nam Phi (South Africa)'),
    SelectItem(id: '161', name: 'Nam Sudan (South Sudan)'),
    SelectItem(id: '162', name: 'Tây Ban Nha (Spain)'),
    SelectItem(id: '163', name: 'Sri Lanka'),
    SelectItem(id: '164', name: 'Sudan'),
    SelectItem(id: '165', name: 'Suriname'),
    SelectItem(id: '166', name: 'Swaziland (Eswatini)'),
    SelectItem(id: '167', name: 'Thụy Điển (Sweden)'),
    SelectItem(id: '168', name: 'Thụy Sĩ (Switzerland)'),
    SelectItem(id: '169', name: 'Syria'),
    SelectItem(id: '170', name: 'Đài Loan (Taiwan)'),
    SelectItem(id: '171', name: 'Tajikistan'),
    SelectItem(id: '172', name: 'Tanzania'),
    SelectItem(id: '173', name: 'Thái Lan (Thailand)'),
    SelectItem(id: '174', name: 'Togo'),
    SelectItem(id: '175', name: 'Tonga'),
    SelectItem(id: '176', name: 'Trinidad và Tobago'),
    SelectItem(id: '177', name: 'Tunisia'),
    SelectItem(id: '178', name: 'Thổ Nhĩ Kỳ (Turkey)'),
    SelectItem(id: '179', name: 'Turkmenistan'),
    SelectItem(id: '180', name: 'Tuvalu'),
    SelectItem(id: '181', name: 'Uganda'),
    SelectItem(id: '182', name: 'Ukraina (Ukraine)'),
    SelectItem(id: '183', name: 'Vương quốc Anh (United Kingdom)'),
    SelectItem(id: '184', name: 'Hoa Kỳ (United States of America)'),
    SelectItem(id: '185', name: 'Uruguay'),
    SelectItem(id: '186', name: 'Uzbekistan'),
    SelectItem(id: '187', name: 'Vanuatu'),
    SelectItem(id: '188', name: 'Thành phố Vatican (Vatican City)'),
    SelectItem(id: '189', name: 'Venezuela'),
    SelectItem(id: '191', name: 'Yemen'),
    SelectItem(id: '192', name: 'Zambia'),
    SelectItem(id: '193', name: 'Zimbabwe'),
  ];
}
